version: "2"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moolahlah
    volumes:
      - .:/var/www
    ports:
      - "${PORT}:${PORT}"
    networks:
      - moolahlah-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: "${MONGO_HOST}"
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - moolahlah-network

networks:
  moolahlah-network:
    driver: bridge