version: "2"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moolahlah
    volumes:
      - .:/var/www
    ports:
      - "${PORT}:${PORT}"
    networks:
      - moolahlah-network
    depends_on:
      - mysqldb
      - redis

  mysqldb:
    image: mysql:5.7.24
    container_name: "${MYSQL_HOST}"
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./temp/mysql:/var/lib/mysql
    networks:
      - moolahlah-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - moolahlah-network

networks:
  moolahlah-network:
    driver: bridge