version: "2"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moolahlah
    volumes:
      - .:/var/www
    ports:
      - "${PORT}:${PORT}"
    networks:
      - moolahlah-network
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    container_name: "${MONGO_HOST}"
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./temp/db:/data/db
    networks:
      - moolahlah-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - moolahlah-network

networks:
  moolahlah-network:
    driver: bridge